export const CRAFT_CONTRACT = `
ADVANCED NATIVE TOOLKIT (optional, implemented):
Scene camera:{position:[x,y,z],target:[x,y,z],zoom,depthOfField:boolean,focusDistance,aperture,animation:{position?,target?,zoom?,focusDistance?,aperture?}}. Camera position/target keys use three-value vectors, other keys scalar. All keys use {time,value,ease:"linear"|"smooth"|"hold",influenceIn?:0.1–100,influenceOut?:0.1–100}. Incoming/outgoing influence changes acceleration without adding sampled keys. Camera looks toward target, default useful position [width/2,height/2,-width], target [width/2,height/2,0], zoom width. A 2D layer ignores the camera. Use real spatial depth; never approximate requested camera motion using dozens of diagonal 2D rectangles.
Effects blur/glow/shadow additionally accept animation:[{time,value,ease,influenceIn?,influenceOut?}] to animate their amount (blur/shadow 0–200; glow 0–10).
Scene motionBlur:{shutterAngle:0–720,samples:integer 2–64}; prefer 180–240 and 8–16. Layer threeD:{z,rotationX,rotationY,animation:{z?,rotationX?,rotationY?}} makes the layer 3D. Position/scale remain two-component channels; animate depth using z. No 3D extrusion, custom shaders, lights, tracking or generative footage are implemented.
New layer types: path and null. path has vector:{vertices:[[x,y],...],inTangents?:[[x,y],...],outTangents?:[[x,y],...],closed:boolean}; 2–256 vertices, tangents are relative offsets with matching counts. Geometry is local to layer position. null creates an editable transform controller; children with parentId use parent-local coordinates. Parent must exist, be unrepeated and same 2D/3D dimension as child, no cycles.
Shape layers path/rectangle/ellipse can use stroke:{color:"#RRGGBB",width,fill:boolean} and trim:{start:0–100,end:0–100,offset:degrees,animation:{start?,end?,offset?}}. Use true outlined paths rather than stacks of filled rectangles. Trim keys are scalar. Stroke width 0.1–2000.
Layers may use masks:[{space?:"source"|"text-box"|"layer-box",path:<vector geometry>,mode:"add"|"subtract",feather:0–1000,expansion:-10000–10000,opacity:0–100,animation:{expansion?,opacity?}}]. For text, use space:"text-box": coordinates run from [0,0] to [layer.width,layer.height], with the glyph centre at [width/2,height/2]. The adapter maps that design box to the actual font anchor, so centre-out masks must be centred at width/2. This avoids clipping letters because text is not a pixel image. For rectangle/ellipse/path masks authored in a [0,width] × [0,height] design box, use space:"layer-box"; this explicitly converts top-left box geometry to the native centered shape anchor. Use that mode rather than assuming a shape has an image-style origin. For footage or explicitly native shape geometry use space:"source" (the legacy default): coordinates are native layer/source pixels, not comp pixels; account for fitted asset dimensions. Up to 8 masks. Use masks for actual reveals, never replace the approved logo with approximate lettering.
Layers may use repeat:{count:integer 2–160,position:[dx,dy,dz],rotation:degreesPerCopy,scale:percentPerCopy,delay:secondsPerCopy}. Native adapter expands this into individually editable layers. All animation keys shift by delay per copy; transform values offset as specified. 400 total expanded layers maximum, 80 authored layers. Keep repeat scale near 100, depth repetitions require threeD. Use restrained densities and intentional spacing, not hundreds of arbitrary accents. Key times start at absolute composition time; repeats must start within duration.
Scene precompositions:[{name,layerIds:[authored layer IDs],collapse:boolean}] groups related layers into editable subcompositions. Repeated families include all their copies. Up to 8 groups, no overlaps; parent and child must stay in the same group. Groups must be uniformly 3D (collapse:true) or 2D (collapse:false). Useful for a depth field, a hero lockup, or a footage overlay stage.
Scene beats:[{time,label,direction}] describes up to 16 chronological visual story beats and becomes native timeline markers. Include opening, development/peak, resolution/hero hold. Use the exact requested duration; allocate a meaningful readable final hold. A seven-second ident generally needs 1–1.5s of hero hold, not seven seconds of constant movement.
Scene soundtrack:{gain:0–1,cues:[{time,duration,type:"rise"|"impact"|"tone"|"air",frequency:20–12000,gain:0–1,pan:-1–1}]} creates an actual stereo WAV track in the native project. Synthesized scores support compositions up to 120 seconds. Maximum 32 cues, each ends within composition. This is restrained synthesized sound design, not licensed music or recorded foley. Typical foundation 45–90Hz tone, short 50–100Hz impact at the resolution, soft air at transitions, sparse rising tones. Uploaded audio remains usable through media layers. Do not add synthesized sound if silence or an existing soundtrack is requested.
QUALITY BAR: Plan the visual sequence before serializing layers. Build one coherent visual idea, deliberate depth/pacing, bold hierarchy and disciplined palette. Match the supplied mark exactly at the final hold. Use native transforms, path reveals and depth only when they serve that idea. An animated title plus a decorative line is insufficient for a requested cinematic ident. Avoid decoration unrelated to brand/story. A quiet brief still deserves precise typography and excellent timing, not mandatory effects. Use uploaded footage, logotypes and reference assets; explain limitations honestly. Revisions should implement specific critique, preserve what works, and keep native editability. This contract supersedes earlier flat-layer limitations.`;
export function validateReview(raw: unknown) {
  if(!raw || typeof raw!=="object")throw Error("Astra returned an invalid review");
  const r=raw as Record<string,unknown>;
  const text=(v:unknown)=>{if(typeof v!=="string"||!v.trim()||v.length>2000)throw Error("Invalid review text");return v;};
  const list=(v:unknown)=>{if(!Array.isArray(v)||v.length>8)throw Error("Invalid review findings");return v.map(text);};
  return {summary:text(r.summary),strengths:list(r.strengths),fixes:list(r.fixes)};
}
