"use client";
/* Native previews require authenticated cookies and must not pass through the image optimizer. */
/* eslint-disable @next/next/no-img-element */
import { useCallback, useEffect, useMemo, useRef, useState } from "react";
import { ArrowLeft, ArrowUp, Check, Download, Film, Layers, Loader2, Plus, Upload, WandSparkles } from "lucide-react";
import type { MotionProject, NativeSnapshot } from "@/lib/motion/schema";
import { readJson } from "@/lib/utils";
import styles from "./motion-studio.module.css";
import { MotionProgress } from "./motion-progress";
type Bridge = { connected: boolean; snapshot: NativeSnapshot | null };
type Overview = { projects: MotionProject[]; bridge: Bridge; astraConfigured: boolean; afterEffectsDetected: boolean };
type ProjectResponse = { project: MotionProject; bridge: Bridge };
async function api<T>(url: string, init?: RequestInit): Promise<T> {
  let response: Response;
  try { response = await fetch(url, init); }
  catch { throw new Error("Motion Design could not reach Athar. Check the connection and retry."); }
  const data = await readJson<T & { error?: string }>(response);
  if (!response.ok) throw new Error(data.error || "Motion Design could not complete that request. Please retry.");
  return data;
}
const busyStates = ["designing", "queued", "working", "encoding"];
export function MotionStudio() {
  const [overview, setOverview] = useState<Overview | null>(null), [project, setProject] = useState<MotionProject | null>(null);
  const [error, setError] = useState(""), [pending, setPending] = useState(false), [brief, setBrief] = useState("");
  const [format, setFormat] = useState("1920x1080"), [duration, setDuration] = useState(6), [fps, setFps] = useState(30);
  const [bridgeReady, setBridgeReady] = useState(false);
  const [setup, setSetup] = useState(false), [uploadName, setUploadName] = useState("");
  const input = useRef<HTMLInputElement>(null), projectId = project?.id;
  const refresh = useCallback(async () => { const data = await api<Overview>("/api/motion"); setOverview(data); }, []);
  useEffect(() => { let alive = true, inFlight = false; const load = async () => { if (inFlight) return; inFlight = true; try { const data = await api<Overview>("/api/motion"); if (alive) { setOverview(data); setError(""); } } catch(e) { if (alive) setError(e instanceof Error ? e.message : "Connection failed"); } finally { inFlight = false; } }; void load(); const timer = setInterval(() => { if (!document.hidden) void load(); }, 5000); return () => { alive = false; clearInterval(timer); }; }, []);
  useEffect(() => { if (!projectId) return; let alive = true, inFlight = false; const load = async () => { if (inFlight) return; inFlight = true; try { const data = await api<ProjectResponse>(`/api/motion/${projectId}`); if (alive) { setProject(data.project); setOverview(o => o ? { ...o, bridge: data.bridge } : o); } } catch { /* Keep the last revision while a request is being written. */ } finally { inFlight = false; } }; const timer = setInterval(() => { if (!document.hidden) void load(); }, 2500); return () => { alive = false; clearInterval(timer); }; }, [projectId]);
  const previousState = useRef<{ id: string; status: string } | null>(null);
  useEffect(() => {
    if (project && previousState.current?.id === project.id && previousState.current.status === "designing") {
      if (project.status === "ready") setBrief("");
      if (project.status === "failed" && project.designJob) setBrief(current => current || project.designJob!.instruction);
    }
    previousState.current = project ? { id: project.id, status: project.status } : null;
  }, [project]);
  const busy = pending || !!project && busyStates.includes(project.status);
  function syncSettings(p: MotionProject) { const settings = p.designJob?.settings ?? p.scene; if(settings && p.mode === "create") {setFormat(`${settings.width}x${settings.height}`);setDuration(settings.duration);setFps(settings.fps);} }
  async function create(mode: "create" | "edit", starter?: string) { setPending(true); setError(""); try { const data = await api<ProjectResponse>("/api/motion", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ name: mode === "create" ? "Untitled motion" : "Composition edit", mode, starter }) }); setProject(data.project); syncSettings(data.project); setBrief(""); await refresh(); } catch(e) { setError(String(e instanceof Error ? e.message : e)); } finally { setPending(false); } }
  async function action(action: string, extra: object = {}) { if (!project) return; setPending(true); setError(""); try { const data = await api<ProjectResponse>(`/api/motion/${project.id}`, { method:"POST", headers:{"Content-Type":"application/json"}, body:JSON.stringify({ action, ...extra }) }); setProject(data.project); if (action === "restore") syncSettings(data.project); } catch(e) { setError(e instanceof Error ? e.message : "Operation failed"); } finally { setPending(false); } }
  async function upload(files: FileList | null) { if (!project || !files?.length) return; setPending(true); setError(""); try { for (const file of Array.from(files)) { if (file.size > 80 * 1024 * 1024) throw new Error(`${file.name}: the limit is 80 MB per asset. Use a trimmed or compressed copy.`); setUploadName(file.name); const data = await api<ProjectResponse>(`/api/motion/${project.id}/assets?name=${encodeURIComponent(file.name)}`, { method:"POST", headers:{"Content-Type":"application/octet-stream"}, body:file }); setProject(data.project); } } catch(e) { setError(e instanceof Error ? e.message : "Upload failed"); } finally { setPending(false); setUploadName(""); if(input.current)input.current.value=""; } }
  async function prepareBridge() { setPending(true); setError(""); try { await api<{ ok?: boolean }>("/api/motion/bridge",{method:"POST"}); setBridgeReady(true); } catch(e) {setError(e instanceof Error ? e.message : "Could not prepare the bridge");} finally {setPending(false);} }
  const bridge = overview?.bridge, scene = project?.scene;
  const visibleProjects = useMemo(
    () => (overview?.projects ?? []).filter((item) => item.name !== "ATHAR — Enter the Trace · Studio study"),
    [overview?.projects]
  );
  const output = (kind: string) => {
    const version = kind === "movie" ? project?.movie : kind === "preview" ? project?.preview : kind === "master" ? project?.master : project?.nativeProject;
    return `/api/motion/${project?.id}?output=${kind}&v=${encodeURIComponent(version ?? "")}`;
  };
  return <section className={styles.studio}>
    <header className={styles.header}><div><p className={styles.eyebrow}>ATHAR / EDITABLE MOTION GRAPHICS</p><h1>Motion design</h1><p>Describe the animation. Astra designs it. After Effects builds editable layers.</p></div><button className={styles.connection} onClick={() => setSetup(!setup)}><span data-connected={bridge?.connected || false}/>{bridge?.connected ? `After Effects ${bridge.snapshot?.version.split(".")[0]} connected` : "Connect After Effects"}</button></header>
    {(setup || (overview && !bridge?.connected && !project)) && <div className={styles.setup}><div><strong>Connect this Mac</strong><p>After Effects and Athar must run on this computer. Keep the bridge window open while working.</p></div><ol><li><button disabled={pending} onClick={()=>void prepareBridge()}>{bridgeReady ? "Bridge prepared ✓" : "Prepare bridge"}</button> <a href="/api/motion/bridge" download>Download bridge <Download size={14}/></a></li><li>In After Effects, enable <b>Allow Scripts to Write Files and Access Network</b> under Settings → Scripting &amp; Expressions.</li><li>Choose File → Scripts → Run Script File, open <b>Athar-After-Effects.jsx</b> from your downloads. Or, after preparing the bridge, run <b>scripts/motion/bridge.jsx</b> in your local Athar folder. It connects automatically.</li></ol><p className={styles.note}>{overview?.afterEffectsDetected ? "After Effects is installed on this Mac." : "After Effects is required for native preview and export."} This connection uses local files; it is separate from a ChatGPT plugin.</p></div>}
    {bridge?.connected && (bridge.snapshot?.capabilities ?? 1) < 6 && <div className={styles.setup}><strong>Update your After Effects connection</strong><p>Prepare the bridge and run it again to study the complete timeline and reuse native reference compositions, effects and animation.</p><button onClick={()=>setSetup(true)}>Show connection steps</button></div>}
    {error && <div className={styles.error} role="alert">{error}</div>}
    {!overview && !error && <p role="status"><Loader2 className={styles.spin} size={18}/> Connecting to your workspace…</p>}
    {!project ? <>
      <div className={styles.intro}>
        <div><p className={styles.eyebrow}>CHOOSE WHAT YOU WANT TO DO</p><h2>Create real motion graphics, not generated video.</h2><p>Use this workspace for animated typography, logos, graphic overlays and effects. The result is a native After Effects composition with editable layers, timing and keyframes.</p></div>
        <div className={styles.workflowChoices}>
          <button disabled={!overview || pending} onClick={() => void create("create")}><span><Plus size={18}/></span><strong>Start a new motion graphic</strong><p>Choose a canvas, add assets, and describe the exact copy, style and timing.</p><small>Best for titles, idents, social graphics and overlays</small></button>
          <button disabled={!overview || pending} onClick={() => void create("edit")}><span><Layers size={18}/></span><strong>Edit an After Effects composition</strong><p>Open the source in After Effects first. Athar studies it, duplicates it, then applies your direction.</p><small>The original composition stays unchanged</small></button>
        </div>
      </div>
      <div className={styles.howItWorks}><div><b>1</b><span><strong>Set the direction</strong><small>Add copy, footage and the intended format.</small></span></div><div><b>2</b><span><strong>Astra designs</strong><small>It plans the layers, hierarchy, motion and timing.</small></span></div><div><b>3</b><span><strong>Build in After Effects</strong><small>Review the real render and continue editing natively.</small></span></div></div>
      <div className={styles.sectionTitle}><h2>Your motion projects</h2><span>{visibleProjects.length} projects</span></div>
      <div className={styles.grid}>{visibleProjects.map(p => <button key={p.id} className={styles.projectCard} onClick={() => {setProject(p);syncSettings(p);setBrief(p.designJob?.instruction ?? "");setError("");}}><div>{p.preview ? <img src={`/api/motion/${p.id}?output=preview&v=${p.updatedAt}`} alt=""/> : <Film size={36}/>}<span>{p.mode === "edit" ? "COMPOSITION EDIT" : "MOTION GRAPHICS"}</span></div><strong>{p.name}</strong><p>{p.scene ? `${p.scene.duration}s · ${p.scene.width} × ${p.scene.height}` : "Add your direction"}</p></button>)}</div>
      {overview && !visibleProjects.length && <p className={styles.emptyProjects}>No motion projects yet. Choose one of the two workflows above to begin.</p>}
    </> : <>
      <div className={styles.projectHeading}><button onClick={() => {setProject(null);setError("");void refresh();}}><ArrowLeft size={16}/> Projects</button><h2>{project.name}</h2><span>{project.referenceComp ? "Create from reference" : project.mode === "edit" ? "Edit composition" : "Create motion"}</span></div>
      <div className={`${styles.workspace} ${busyStates.includes(project.status) ? styles.workspaceBusy : ""}`}>
        <aside className={styles.controls}>
          <div className={styles.sectionTitle}><h3>{project.scene ? "Refine the direction" : "Set the direction"}</h3><span>GPT-6 Astra</span></div>
          {overview && !overview.astraConfigured && <p className={styles.error}>Connect OpenAI in Athar to use Astra.</p>}
          {project.mode === "edit" ? <div className={styles.source}><strong>Source composition</strong><p>{project.baseComp ? `${project.baseComp.name} · ${project.baseComp.layers.length} layers` : "Open the composition you want to edit in After Effects."}</p><button disabled={busy || !bridge?.connected} onClick={() => void action(project.baseComp ? "study-source" : "inspect")}>{project.sourceStudy ? "Refresh source study" : project.baseComp ? "Study source style" : "Study active composition"}</button>{project.baseComp && <button disabled={busy || !bridge?.connected} onClick={()=>void action("inspect")}>Use active composition instead</button>}<small>{project.sourceStudy ? `${project.sourceStudy.frames.length} original frames · ${project.sourceStudy.compositionCount} compositions studied. Captured ${new Date(project.sourceStudy.capturedAt).toLocaleString()}. Refresh after editing the source.` : "Capture the source before designing: Astra needs to see its colours, graphics and animation timing."} The original is duplicated before any changes. Choosing a different source starts a new design.</small><button disabled={busy || !bridge?.connected || !project.baseComp} onClick={()=>void action("reference")}>Create a new piece from the active reference</button></div> : <div className={styles.settings}><label>Canvas<select value={format} disabled={busy} onChange={e=>setFormat(e.target.value)}><option value="1920x1080">Landscape · 1920 × 1080</option><option value="1080x1920">Portrait · 1080 × 1920</option><option value="1080x1080">Square · 1080 × 1080</option><option value="3840x2160">Landscape · 4K</option></select></label><div><label>Seconds<input type="number" min={0.1} max={600} step={0.1} value={duration} disabled={busy} onChange={e=>setDuration(Number(e.target.value))}/></label><label>Frame rate<select value={fps} disabled={busy} onChange={e=>setFps(Number(e.target.value))}>{[24,25,30,50,60].map(n=><option key={n}>{n}</option>)}</select></label></div></div>}
          {project.mode === "create" && <div className={styles.source}><strong>Composition reference</strong><p>{project.referenceComp?.name ?? "Open a reference composition in After Effects. Create a new deliverable using its visual and motion language."}</p><button disabled={busy || !bridge?.connected} onClick={()=>void action(project.referenceComp ? "study-source" : "reference")}>{project.referenceComp ? "Refresh reference study" : "Study active composition as reference"}</button>{project.referenceComp && <button disabled={busy || !bridge?.connected} onClick={()=>void action("reference")}>Choose the active composition instead</button>}<small>Your canvas, duration and deliverable stay independent of the reference. Native elements can be reused with their effects and animation intact. The original remains unchanged.</small></div>}
          <div className={styles.assets}><div className={styles.sectionTitle}><h3>Footage &amp; elements</h3><button disabled={busy} aria-label="Upload assets" onClick={()=>input.current?.click()}><Plus size={16}/></button></div><input ref={input} type="file" hidden multiple accept=".png,.jpg,.jpeg,.webp,.mp4,.mov,.wav,.mp3" onChange={e=>void upload(e.target.files)}/>{project.assets.length ? <ul>{project.assets.map(a=><li key={a.id}><span>{a.type.startsWith("video")?<Film size={14}/>:<Layers size={14}/>} {a.name}</span><small>{(a.bytes/1048576).toFixed(1)} MB</small></li>)}</ul> : <button className={styles.upload} disabled={busy} onClick={()=>input.current?.click()}><Upload size={20}/><strong>Add footage, images or audio</strong><small>80 MB per file · Originals stay intact</small></button>}{uploadName && <p role="status">Uploading {uploadName}…</p>}</div>
          <label className={styles.direction}>Creative direction<textarea value={brief} disabled={busy} onChange={e=>setBrief(e.target.value)} placeholder={scene ? "Make the headline arrive later. Keep the footage clean. Add a softer exit…" : "Describe the story, exact copy, visual style and timing. Mention uploaded files by name…"} maxLength={16000} rows={7}/></label>
          <button className={styles.primary} disabled={busy || !brief.trim() || !overview?.astraConfigured || (project.mode === "edit" && (!project.baseComp || !project.sourceStudy))} onClick={()=>{const [width,height]=format.split("x").map(Number);void action("design",{instruction:brief,settings:{width,height,duration,fps}});}}>{project.status === "designing" ? <Loader2 className={styles.spin} size={17}/> : <ArrowUp size={17}/>} {project.status === "designing" ? project.designJob?.phase === "study" ? "Studying your reference…" : "Designing your motion…" : scene ? "Direct revision" : "Design with Astra"}</button><p className={styles.note}>Astra designs the layers and timing using your OpenAI connection. Review the design, then build it in After Effects.</p>
        </aside>
        <div className={styles.stage}>
          <div className={styles.stageTop}><span><span className={styles.dot}/>{busyStates.includes(project.status) ? project.status === "designing" ? project.designJob?.purpose === "review" ? "Astra is reviewing the native frames…" : project.designJob?.phase === "study" ? "Astra is studying the reference and planning the treatment…" : "Astra is designing…" : project.status === "encoding" ? "Preparing playable video…" : project.commandKind === "inspect" ? "Studying the original composition…" : project.status === "queued" ? "Waiting for After Effects…" : project.commandKind === "render" ? "Rendering in After Effects…" : "Building native layers…" : project.preview ? "Native After Effects preview" : scene ? "Design ready to build" : "Your canvas"}</span>{scene && <small>{scene.width} × {scene.height} · {scene.duration}s · {scene.fps} fps</small>}</div>
          {busyStates.includes(project.status) && <MotionProgress project={project}/>}
          {project.error && <div className={styles.error} role="alert">{project.error}{project.status === "failed" && project.designJob && (project.designJob.failureCode === "output_limit" || project.error.includes("max_output_tokens")) && <button disabled={busy} className={styles.recover} onClick={() => void action("retry-design")}>Retry saved direction</button>}</div>}
          {!busyStates.includes(project.status) && <div className={styles.preview}>{project.movie ? <video src={output("movie")} controls poster={project.preview?output("preview"):undefined}/> : project.preview ? <img src={output("preview")} alt="Frame rendered by After Effects"/> : <div><div className={styles.stageIcon}>{busy ? <Loader2 className={styles.spin} size={32}/> : <WandSparkles size={32}/>}</div><h2>{scene ? "Ready for After Effects" : "Start with your direction"}</h2><p>{scene ? "Build this design to see the actual composition here." : "Create motion graphics from scratch, or add animated elements over uploaded footage."}</p></div>}</div>}
          {project.sourceStudy && !busyStates.includes(project.status) && <details className={styles.frameReview}><summary>Original art direction · {project.sourceStudy.frames.length} reference frames</summary><p>These come from {(project.referenceComp ?? project.baseComp)?.name}, not the generated revision. Astra also receives native colours, typography, effects and sampled keyframes.{project.sourceStudy.truncated ? " Some properties or nested compositions exceeded the inspection limits." : ""} {project.sourceStudy.capturedProperties ? `${project.sourceStudy.capturedProperties} properties captured. ` : ""}{project.sourceStudy.unreadableProperties ? `${project.sourceStudy.unreadableProperties} properties could not be read; native reuse may still preserve them. ` : ""}Sampled frames cannot establish every transition or sound.</p><div className={styles.frames}>{project.sourceStudy.frames.map((f,i)=><a key={f.file} href={`/api/motion/${project.id}?output=source-${i}`} target="_blank" rel="noreferrer"><img src={`/api/motion/${project.id}?output=source-${i}&v=${encodeURIComponent(f.file)}`} alt={`Original source at ${f.time.toFixed(2)} seconds`}/><span>{f.time.toFixed(2)}s</span></a>)}</div></details>}
          {project.referenceTreatment && <details className={styles.frameReview}><summary>Creative treatment · from reference to your brief</summary>{(["visualLanguage","animationLanguage","adaptationPlan","nativeReuse"] as const).map(key=><div key={key}><h4>{({visualLanguage:"Visual language",animationLanguage:"Motion language",adaptationPlan:"Your deliverable",nativeReuse:"Native reuse"})[key]}</h4><p>{project.referenceTreatment![key]}</p></div>)}{project.referenceTreatment.limitations.length>0 && <ul>{project.referenceTreatment.limitations.map((l,i)=><li key={i}>{l}</li>)}</ul>}</details>}
          {scene?.styleMatch && !busyStates.includes(project.status) && <div className={styles.frameReview}><h3>How this follows your source</h3>{(["palette","typography","motion","layout"] as const).map(key=><div key={key}><h4>{key === "palette" ? "Colour palette" : key === "typography" ? "Typography" : key === "motion" ? "Animation language" : "Graphic language & layout"}</h4><p>{scene.styleMatch![key]}</p></div>)}{scene.styleMatch.limitations.length>0 && <><h4>Matching limitations</h4><ul>{scene.styleMatch.limitations.map((text,i)=><li key={i}>{text}</li>)}</ul></>}<small>Astra’s design rationale. Compare the actual render with the source before approving.</small></div>}
          {!!project.frames?.length && !busyStates.includes(project.status) && <div className={styles.frameReview}><div className={styles.sectionTitle}><h3>Review the real frames</h3><button disabled={busy || !overview?.astraConfigured} onClick={()=>void action("review")}><WandSparkles size={15}/> Review with Astra</button></div><p>Native frames sampled across the motion. A still-frame review is not final approval: play the rendered film to check transitions, pacing and sound.</p><div className={styles.frames}>{project.frames.map((file,i)=><a key={file} href={`/api/motion/${project.id}?output=frame-${i}`} target="_blank" rel="noreferrer"><img src={`/api/motion/${project.id}?output=frame-${i}&v=${encodeURIComponent(file)}`} alt={`Rendered frame at ${(project.frameTimes?.[i] ?? (i*0.2+0.1)*(scene?.duration??0)).toFixed(2)} seconds`}/><span>{(project.frameTimes?.[i] ?? (i*0.2+0.1)*(scene?.duration??0)).toFixed(2)}s</span></a>)}</div>{project.review && <div className={styles.review}><strong>Astra’s visual review</strong><p>{project.review.summary}</p>{project.review.strengths.length>0 && <ul>{project.review.strengths.map((text,i)=><li key={i}>{text}</li>)}</ul>}{project.review.fixes.length>0 && <><h4>Next revision</h4><ol>{project.review.fixes.map((text,i)=><li key={i}>{text}</li>)}</ol><button disabled={busy} onClick={()=>setBrief(`Refine the existing design using these observations from the native frames. Preserve the successful elements and approved assets.\n\n${project.review!.fixes.join("\n\n")}`)}>Use these notes as my direction</button></>}</div>}</div>}
          {!!scene?.nativeModules?.length && <div className={styles.frameReview}><h3>Native elements from your reference</h3><p>These use the original composition structure, effects, expressions and animation. Text and layout adaptations are applied to separate copies.</p><ul>{scene.nativeModules.map(m=><li key={m.id}><strong>{m.name}</strong> — {m.sourceName} · {m.changes.length} adaptations</li>)}</ul></div>}
          {scene?.beats && <div className={styles.beats}>{scene.beats.map(b=><div key={b.time}><small>{b.time.toFixed(1)}s</small><strong>{b.label}</strong><p>{b.direction}</p></div>)}</div>}
          {scene && <div className={styles.design}><div className={styles.sectionTitle}><h3>{scene.name}</h3><span>{scene.layers.reduce((n,l)=>n+(l.repeat?.count??1),0)} editable layers{scene.changes.length ? ` · ${scene.changes.length} source edits` : ""}</span></div><p>{scene.summary}</p>{scene.transparent && <p className={styles.note}>Transparent overlay. Use the native master for compositing; the MP4 preview displays transparent areas against black.</p>}<div className={styles.timeline} aria-label="Designed layer timing">{scene.layers.map(l=><div key={l.id}><span title={l.name}>{l.name}</span><div><i style={{left:`${l.start/scene.duration*100}%`,width:`${(l.end-l.start)/scene.duration*100}%`}} title={`${l.start}s – ${l.end}s`}/></div><small>{Object.values(l.animation).reduce((n,keys)=>n+keys.length,0)} keys</small></div>)}</div><div className={styles.actions}><button className={styles.primary} disabled={busy || !bridge?.connected} onClick={()=>void action("build")}><Layers size={16}/>{project.nativeCompId ? "Rebuild in After Effects" : "Build in After Effects"}</button><button disabled={busy || !bridge?.connected || !project.nativeCompId} onClick={()=>void action("render")}><Film size={16}/> Render video</button>{project.nativeProject && <a href={output("project")} download><Download size={16}/> Editable project</a>}{project.master && <a href={output("master")} download><Download size={16}/> {scene.transparent ? "Master with transparency" : "Master video"}</a>}{project.movie && <a href={output("movie")+"&download=1"} download><Download size={16}/> Video</a>}</div>{!bridge?.connected && <p className={styles.note}>Connect After Effects to build or render this design.</p>}</div>}
          {!!project.revisions.length && <details className={styles.history}><summary>Direction history · {project.revisions.length} revisions</summary>{project.revisions.map((r,i)=><div key={r.at}><span><strong>Revision {i+1}</strong><p>{r.brief}</p></span><button disabled={busy} onClick={()=>void action("restore",{index:i})}><Check size={14}/> Use revision</button></div>)}</details>}
          <p className={styles.scope}>Native tools: 3D layers and cameras, vector paths and reveals, masks, transform controllers, repeated layers, custom easing, motion blur and timed sound. Frame reviews use sampled stills; review the moving film and audio before delivery.</p>
        </div>
      </div>
    </>}
  </section>;
}
